### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by AzizKpln** [X-ZIGZAG/X-ZIGZAG#1]
Hi, thanks for sharing a project like this on github. 

I successfully set up the server code on a remote server and can access the web panel smoothly through port 4000. For the client side, I downloaded the code to my Windows virtual machine and compiled it using Visual Studio. Before compiling, I replaced 'http://yourserverip:port/' with my own server details. However, when I ran the executable on the virtual machine, I couldn't connect to my remote web panel server. I tried compiling it with different port numbers such as 9999, 4000, 8080, and 8000, and configured it according to the format 'http://yourserverip:port/' as stated in the installation instructions, but there is still an issue with the connection. Is there something like an anti-VM feature blocking it, or is it another issue

**Comment by AzizKpln** [comment]
![Ekran Alıntısı](https://github.com/user-attachments/assets/a41df28c-f37b-4e79-957b-0c503b2b60df)

I tried to see the connections made with procmon i filtred it for tcp and udp connections but when i execute the exe, no connections is being established or made. 

![sd](https://github.com/user-attachments/assets/f07035a5-f55c-4812-bf96-6202c991e2c9)

Also tried to see any connections to the ip address via wireshark but nothing showed up.

**Comment by X-SP33D** [comment]
Hi AzizKpln !
thank you for reaching out! The issue you're encountering might be due to the program's built-in **anti-analytics** system. This system is designed to prevent the application from running in virtual environments like **VMs**, **sandboxes**, and certain **monitoring tools** for security purposes. This could be why you're unable to connect to the remote web panel server when running it on your virtual machine.

To resolve this, I would suggest trying to run the client on a physical machine instead of a VM. Let me know if that works, or if you need any further assistance!

**Comment by AzizKpln** [comment]
hello again, thanks for the reply. I have another windows pc i tried opening the project there but again, the connection is not established to c2.

**Comment by AzizKpln** [comment]
oh it worked

**Comment by X-SP33D** [comment]
Thanks for the update! I'm Glad to hear it's working. 
Feel free to reach out if you encounter any other issues or have any suggestions for improvements
